import type { Facility, MapCenter } from './types';

interface MockFacilityOffset extends Omit<Facility, 'lat' | 'lng'> {
  latOffset: number;
  lngOffset: number;
}

const MOCK_FACILITY_OFFSETS: MockFacilityOffset[] = [
  {
    id: 'f1',
    name: 'OO 주민센터',
    mainCategory: '생활지원',
    subCategory: '주민센터',
    address: 'OO시 OO구 OO동',
    detailAddress: '[상세 주소]',
    latOffset: 0.0009,
    lngOffset: 0.0025,
    distanceFromHome: '0.6km',
    phone: '02-1234-5678',
    operatingHours: '09:00-18:00(주말 휴무)',
  },
  {
    id: 'f2',
    name: 'OO 복지관',
    mainCategory: '생활지원',
    subCategory: '복지관',
    address: 'OO시 OO구 OO동',
    detailAddress: '[상세 주소]',
    latOffset: 0.0049,
    lngOffset: -0.0025,
    distanceFromHome: '0.9km',
    phone: '02-2345-6789',
    operatingHours: '09:00-18:00(주말 휴무)',
  },
  {
    id: 'f3',
    name: '우리 약국',
    mainCategory: '건강·의료',
    subCategory: '약국',
    address: 'OO시 OO구 OO동',
    detailAddress: '[상세 주소]',
    latOffset: -0.0041,
    lngOffset: -0.0085,
    distanceFromHome: '0.4km',
    phone: '02-3456-7890',
    operatingHours: '09:00-21:00(연중무휴)',
  },
  {
    id: 'f4',
    name: 'OO 약국',
    mainCategory: '건강·의료',
    subCategory: '약국',
    address: 'OO시 OO구 OO동',
    detailAddress: '[상세 주소]',
    latOffset: -0.0011,
    lngOffset: 0.0065,
    distanceFromHome: '1.1km',
    phone: '02-4567-8901',
    operatingHours: '09:00-20:00(주말 휴무)',
  },
  {
    id: 'f5',
    name: '동행센터',
    mainCategory: '생활지원',
    subCategory: '동행센터',
    address: 'OO시 OO구 OO동',
    detailAddress: '[상세 주소]',
    latOffset: 0.0069,
    lngOffset: 0.0065,
    distanceFromHome: '1.3km',
    phone: '02-5678-9012',
    operatingHours: '09:00-18:00(주말 휴무)',
  },
  {
    id: 'f6',
    name: 'OO 보건소',
    mainCategory: '건강·의료',
    subCategory: '보건소',
    address: 'OO시 OO구 OO동',
    detailAddress: '[상세 주소]',
    latOffset: -0.0071,
    lngOffset: -0.0005,
    distanceFromHome: '1.5km',
    phone: '02-6789-0123',
    operatingHours: '09:00-18:00(주말 휴무)',
  },
  {
    id: 'f7',
    name: '평생교육원',
    mainCategory: '배움·일자리',
    subCategory: '평생교육원',
    address: 'OO시 OO구 OO동',
    detailAddress: '[상세 주소]',
    latOffset: -0.0031,
    lngOffset: 0.0095,
    distanceFromHome: '1.7km',
    phone: '02-7890-1234',
    operatingHours: '09:00-18:00(주말 휴무)',
  },
  {
    id: 'f8',
    name: 'OO 병원',
    mainCategory: '건강·의료',
    subCategory: '병원',
    address: 'OO시 OO구 OO동',
    detailAddress: '[상세 주소]',
    latOffset: 0.0099,
    lngOffset: -0.0055,
    distanceFromHome: '2.0km',
    phone: '02-8901-2345',
    operatingHours: '08:30-19:00(토요일 09:00-13:00)',
  },
  {
    id: 'f9',
    name: 'OO 경로당',
    mainCategory: '문화',
    subCategory: '경로당',
    address: 'OO시 OO구 OO동',
    detailAddress: '[상세 주소]',
    latOffset: 0.0029,
    lngOffset: -0.0135,
    distanceFromHome: '1.0km',
    phone: '02-9012-3456',
    operatingHours: '09:00-17:00(주말 휴무)',
  },
  {
    id: 'f10',
    name: 'OO 일자리센터',
    mainCategory: '배움·일자리',
    subCategory: '일자리센터',
    address: 'OO시 OO구 OO동',
    detailAddress: '[상세 주소]',
    latOffset: -0.0101,
    lngOffset: 0.0055,
    distanceFromHome: '2.3km',
    phone: '02-0123-4567',
    operatingHours: '09:00-18:00(주말 휴무)',
  },
];

// 카카오 로컬 API 키가 없거나 실패했을 때 쓰는 대체 데이터.
// 실제 데이터처럼 보이도록 지도 중심(내 위치) 기준 상대 오프셋을 절대 좌표로 변환한다.
export const getMockFacilitiesNear = (center: MapCenter): Facility[] =>
  MOCK_FACILITY_OFFSETS.map(({ latOffset, lngOffset, ...rest }) => ({
    ...rest,
    lat: center.lat + latOffset,
    lng: center.lng + lngOffset,
  }));
