import type { Facility } from './types';

export const mockFacilities: Facility[] = [
  {
    id: '1',
    name: '살핌종합복지관',
    category: '복지관',
    address: '서울특별시 강남구 테헤란로 120',
    lat: 37.501,
    lng: 127.039,
    distance: '450m',
    phone: '02-1234-5678',
    operatingHours: '평일 09:00 - 18:00',
    description: '지역 주민을 위한 상담, 돌봄, 식사 지원, 여가 프로그램을 운영하는 종합복지시설입니다.',
    services: ['복지 상담', '무료 급식', '돌봄 프로그램', '여가 활동'],
    tags: ['상담 가능', '식사 지원', '예약 필요'],
  },
  {
    id: '2',
    name: '역삼1동 주민센터',
    category: '주민센터',
    address: '서울특별시 강남구 역삼로 135',
    lat: 37.499,
    lng: 127.033,
    distance: '720m',
    phone: '02-2345-6789',
    operatingHours: '평일 09:00 - 18:00',
    description: '주민등록, 복지 신청, 생활 민원 처리를 지원하는 행정복지센터입니다.',
    services: ['복지급여 신청', '민원 서류 발급', '주민 상담'],
    tags: ['민원 처리', '복지 신청'],
  },
  {
    id: '3',
    name: '강남구 보건소',
    category: '보건소',
    address: '서울특별시 강남구 선릉로 668',
    lat: 37.516,
    lng: 127.042,
    distance: '1.2km',
    phone: '02-3456-7890',
    operatingHours: '평일 09:00 - 18:00',
    description: '건강 상담, 예방접종, 만성질환 관리 등 공공 보건 서비스를 제공합니다.',
    services: ['건강 상담', '예방접종', '만성질환 관리', '검진 안내'],
    tags: ['건강 상담', '검진'],
  },
  {
    id: '4',
    name: '우리동네 내과의원',
    category: '병원',
    address: '서울특별시 강남구 논현로 85',
    lat: 37.493,
    lng: 127.029,
    distance: '1.6km',
    phone: '02-4567-8901',
    operatingHours: '평일 08:30 - 19:00, 토요일 09:00 - 13:00',
    description: '일반 진료와 만성질환 진료를 받을 수 있는 동네 의원입니다.',
    services: ['일반 진료', '처방', '혈압 관리'],
    tags: ['토요일 운영', '처방 가능'],
  },
  {
    id: '5',
    name: '햇살약국',
    category: '약국',
    address: '서울특별시 강남구 봉은사로 20',
    lat: 37.505,
    lng: 127.025,
    distance: '1.9km',
    phone: '02-5678-9012',
    operatingHours: '매일 09:00 - 21:00',
    description: '처방 조제와 일반 의약품 상담이 가능한 약국입니다.',
    services: ['처방 조제', '복약 상담', '상비약 판매'],
    tags: ['야간 운영', '복약 상담'],
  },
];
