import type { Facility, MapCenter } from './types';

interface MockFacilityOffset extends Omit<Facility, 'lat' | 'lng'> {
  latOffset: number;
  lngOffset: number;
}

const MOCK_FACILITY_OFFSETS: MockFacilityOffset[] = [
  {
    id: 'f1',
    name: 'OO 주민센터',
    mainCategory: '생활지원',
    subCategory: '주민센터',
    address: 'OO시 OO구 OO동',
    detailAddress: '[상세 주소]',
    latOffset: 0.0009,
    lngOffset: 0.0025,
    distanceFromHome: '0.6km',
    phone: '02-1234-5678',
    operatingHours: '09:00-18:00(주말 휴무)',
  },
  {
    id: 'f2',
    name: 'OO 복지관',
    mainCategory: '생활지원',
    subCategory: '복지관',
    address: 'OO시 OO구 OO동',
    detailAddress: '[상세 주소]',
    latOffset: 0.0049,
    lngOffset: -0.0025,
    distanceFromHome: '0.9km',
    phone: '02-2345-6789',
    operatingHours: '09:00-18:00(주말 휴무)',
  },
  {
    id: 'f3',
    name: '우리 약국',
    mainCategory: '건강·의료',
    subCategory: '약국',
    address: 'OO시 OO구 OO동',
    detailAddress: '[상세 주소]',
    latOffset: -0.0041,
    lngOffset: -0.0085,
    distanceFromHome: '0.4km',
    phone: '02-3456-7890',
    operatingHours: '09:00-21:00(연중무휴)',
  },
  {
    id: 'f4',
    name: 'OO 치매안심센터',
    mainCategory: '건강·의료',
    subCategory: '치매센터',
    address: 'OO시 OO구 OO동',
    detailAddress: '[상세 주소]',
    latOffset: -0.0011,
    lngOffset: 0.0065,
    distanceFromHome: '1.1km',
    phone: '02-4567-8901',
    operatingHours: '09:00-20:00(주말 휴무)',
  },
  {
    id: 'f5',
    name: 'OO 무료급식소',
    mainCategory: '생활지원',
    subCategory: '무료급식',
    address: 'OO시 OO구 OO동',
    detailAddress: '[상세 주소]',
    latOffset: 0.0069,
    lngOffset: 0.0065,
    distanceFromHome: '1.3km',
    phone: '02-5678-9012',
    operatingHours: '09:00-18:00(주말 휴무)',
  },
  {
    id: 'f6',
    name: 'OO 보건소',
    mainCategory: '건강·의료',
    subCategory: '보건소',
    address: 'OO시 OO구 OO동',
    detailAddress: '[상세 주소]',
    latOffset: -0.0071,
    lngOffset: -0.0005,
    distanceFromHome: '1.5km',
    phone: '02-6789-0123',
    operatingHours: '09:00-18:00(주말 휴무)',
  },
  {
    id: 'f7',
    name: '평생교육원',
    mainCategory: '배움·일자리',
    subCategory: '평생교육원',
    address: 'OO시 OO구 OO동',
    detailAddress: '[상세 주소]',
    latOffset: -0.0031,
    lngOffset: 0.0095,
    distanceFromHome: '1.7km',
    phone: '02-7890-1234',
    operatingHours: '09:00-18:00(주말 휴무)',
  },
  {
    id: 'f8',
    name: 'OO 병원',
    mainCategory: '건강·의료',
    subCategory: '병원',
    address: 'OO시 OO구 OO동',
    detailAddress: '[상세 주소]',
    latOffset: 0.0099,
    lngOffset: -0.0055,
    distanceFromHome: '2.0km',
    phone: '02-8901-2345',
    operatingHours: '08:30-19:00(토요일 09:00-13:00)',
  },
  {
    id: 'f9',
    name: 'OO 도서관',
    mainCategory: '문화',
    subCategory: '도서관',
    address: 'OO시 OO구 OO동',
    detailAddress: '[상세 주소]',
    latOffset: 0.0029,
    lngOffset: -0.0135,
    distanceFromHome: '1.0km',
    phone: '02-9012-3456',
    operatingHours: '09:00-17:00(주말 휴무)',
  },
  {
    id: 'f10',
    name: 'OO 노인일자리기관',
    mainCategory: '배움·일자리',
    subCategory: '노인 일자리기관',
    address: 'OO시 OO구 OO동',
    detailAddress: '[상세 주소]',
    latOffset: -0.0101,
    lngOffset: 0.0055,
    distanceFromHome: '2.3km',
    phone: '02-0123-4567',
    operatingHours: '09:00-18:00(주말 휴무)',
  },
  {
    id: 'f11',
    name: 'OO 생활지원센터',
    mainCategory: '생활지원',
    subCategory: '생활지원센터',
    address: 'OO시 OO구 OO동',
    latOffset: 0.008,
    lngOffset: 0.009,
    distanceFromHome: '1.6km',
    phone: '02-1111-2222',
    operatingHours: '09:00-18:00(주말 휴무)',
  },
  {
    id: 'f12',
    name: 'OO 요양원',
    mainCategory: '생활지원',
    subCategory: '요양시설',
    address: 'OO시 OO구 OO동',
    latOffset: -0.008,
    lngOffset: 0.008,
    distanceFromHome: '1.8km',
    phone: '02-2222-3333',
  },
  {
    id: 'f13',
    name: 'OO 돌봄센터',
    mainCategory: '생활지원',
    subCategory: '돌봄시설',
    address: 'OO시 OO구 OO동',
    latOffset: 0.007,
    lngOffset: -0.009,
    distanceFromHome: '1.9km',
    phone: '02-3333-4444',
  },
  {
    id: 'f14',
    name: 'OO 문화센터',
    mainCategory: '문화',
    subCategory: '문화센터',
    address: 'OO시 OO구 OO동',
    latOffset: -0.006,
    lngOffset: -0.01,
    distanceFromHome: '1.4km',
    phone: '02-4444-5555',
  },
  {
    id: 'f15',
    name: 'OO 체육관',
    mainCategory: '문화',
    subCategory: '체육관',
    address: 'OO시 OO구 OO동',
    latOffset: 0.005,
    lngOffset: 0.011,
    distanceFromHome: '1.5km',
    phone: '02-5555-6666',
  },
  {
    id: 'f16',
    name: 'OO 디지털배움터',
    mainCategory: '배움·일자리',
    subCategory: '디지털 배움터',
    address: 'OO시 OO구 OO동',
    latOffset: -0.009,
    lngOffset: -0.007,
    distanceFromHome: '2.1km',
    phone: '02-6666-7777',
  },
  {
    id: 'f17',
    name: 'OO 시니어클럽',
    mainCategory: '배움·일자리',
    subCategory: '시니어클럽',
    address: 'OO시 OO구 OO동',
    latOffset: 0.01,
    lngOffset: 0.002,
    distanceFromHome: '2.2km',
    phone: '02-7777-8888',
  },
];

// 카카오 로컬 API 키가 없거나 실패했을 때 쓰는 대체 데이터.
// 실제 데이터처럼 보이도록 지도 중심(집 주소) 기준 상대 오프셋을 절대 좌표로 변환한다.
export const getMockFacilitiesNear = (center: MapCenter): Facility[] =>
  MOCK_FACILITY_OFFSETS.map(({ latOffset, lngOffset, ...rest }) => ({
    ...rest,
    lat: center.lat + latOffset,
    lng: center.lng + lngOffset,
  }));
